spring:
  datasource:
    url: jdbc:mysql://mysql:3306/admin_db?useSSL=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
        generate_statistics: false
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
        namespace: public
        group: DEFAULT_GROUP
        service: admin-service
        register-enabled: true
        ip: ${spring.cloud.client.ip-address}
        port: ${server.port}

server:
  port: 8090
  servlet:
    context-path: /admin
    session:
      timeout: 3600s
  tomcat:
    max-threads: 200
    min-spare-threads: 10
    connection-timeout: 60000

application:
  name: admin-service
  version: 1.0.0
  description: 智慧城市后台管理服务

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /actuator
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

logging:
  level:
    root: WARN
    com.smartcity.adminservice: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
  file:
    name: /var/log/admin-service/admin-service.log
    max-size: 100MB
    max-history: 30
    total-size-cap: 1GB

security:
  basic:
    enabled: false

# 生产环境特定配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
    registry-fetch-interval-seconds: 30
    heartbeat-executor-thread-pool-size: 2
    eureka-service-url-poll-interval-seconds: 300
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 90
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health
