server:
  port: 8080

spring:
  profiles:
    active: prod
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
        - id: traffic-service
          uri: lb://traffic-service
          predicates:
            - Path=/api/traffic/**
          filters:
            - StripPrefix=1
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY

 eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-prod:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90