server:
  port: 8761

spring:
  application:
    name: eureka-server
  profiles:
    active: prod

eureka:
  instance:
    hostname: eureka-server
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: true
    evictionIntervalTimerInMs: 30000