server:
  port: 8082

spring:
  profiles:
    active: test
  application:
    name: traffic-service

logging:
  level:
    root: INFO
    com.smartcity: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-test:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}