server:
  port: 8082
  tomcat:
    threads:
      max: 200
      min-spare: 10

spring:
  profiles:
    active: prod
  application:
    name: traffic-service

logging:
  level:
    root: WARN
    com.smartcity: INFO
  file:
    name: /logs/traffic-service.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-prod:8761/eureka/
    registryFetchIntervalSeconds: 30
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}
    leaseRenewalIntervalInSeconds: 30
    leaseExpirationDurationInSeconds: 90