spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://localhost:3306/smartcitydb_test?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: test_user
    password: test_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8081

logging:
  level:
    root: INFO
    com.smartcity: DEBUG

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-test:8761/eureka/
  instance:
    preferIpAddress: true
    instanceId: ${spring.cloud.client.ip-address}:${server.port}